version: '3.8'

volumes:
  postgres:

networks:
  hackathon:
    driver: bridge

services:
  
  postgres: 
    image: postgres:14.2-alpine
    restart: always
    networks:
      - hackathon
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: hackathon
      POSTGRES_USER: hackathon
    ports: 
      - "5432:5432"
